version: "3.7"

services:
  alquileres:
    build: alquiler-BarrenecheaMartinez/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/alquileres?authSource=admin
    depends_on:
      - mongo
  estaciones:
    build: estaciones-2-BarrenecheaMartinez/
    ports:
      - "4040:4040"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/estaciones2?authSource=admin
      - SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
  pasarela:
    build: pasarela/
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/pasarela?authSource=admin
      - SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
  usuarios:
    build: usuarios/
    ports:
      - "5115:5115"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/usuarios?authSource=admin
      - SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
  mongo: 
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express: 
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - sql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: practicas
      MYSQL_DATABASE: arso
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongo_data:
  sql_data: