FROM --platform=linux/amd64 maven:3.8.5-jdk-8 AS builder

WORKDIR /app/
COPY pom.xml .
RUN mvn -e -B dependency:resolve
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:8
COPY --from=builder /app/target/estaciones-2-BarrenecheaMartinez-0.0.1-SNAPSHOT.jar /root.jar
CMD ["java", "-jar", "/root.jar"]

EXPOSE 4040